import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Link from "next/link";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Dummy from "@/components/Dummy";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Codere</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="keywords"
          content="nextjs, huntingcoder blog, hunting coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/src.js"></Script> */}

      <nav className={styles.mainnav}>
        <ul>
          <li className={styles.navItem}>
            <Link href="/">Home</Link>
          </li>

          <li className={styles.navItem}>
            <Link href="/about">About</Link>
          </li>

          <li className={styles.navItem}>
            <Link href="/blog">Blog </Link>
          </li>

          <li className={styles.navItem}>
            <Link href="/contact">Contact</Link>
          </li>
        </ul>
      </nav>

      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className={styles.center}>Hunting</h1>
          <div className={styles.thirteen}>
            <h1>Coder</h1>
          </div>
        </div>
        <div className={styles.center}>
          <p>A blog by hunting coder for hunting coder</p>
        </div>

        <Dummy></Dummy>

        <div className={styles.blogs}>
          <h2>Popula Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2023 ?</h3>
            <p>JavaScript is a language used fo design logic for the web.</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2023 ?</h3>
            <p>JavaScript is a language used fo design logic for the web.</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2023 ?</h3>
            <p>JavaScript is a language used fo design logic for the web.</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2023 ?</h3>
            <p>JavaScript is a language used fo design logic for the web.</p>
          </div>
        </div>
        {/* <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </>
  );
}
